void SaveRootFileForLimit_dineutrino_v2(bool save){
  if(!save) return;
  //char NewFileName[500]; sprintf(NewFileName, "/publicfs/cms/user/yutz/Tprime/2017_dineutrino/shape_dineutrino.root");
  char NewFileName[500]; sprintf(NewFileName, "shape_dineutrino.root");
  TFile f(NewFileName,"new");

  cout<<"this step is ok 1"<<endl;

  //TH1F *background=(TH1F*)histo_PRE->Clone();
  //background->SetName("background");
  //background->Write();
  ZToNuNu->SetName("ZToNuNu"); 
  QCD    ->SetName("QCD"); 
  WToLNu ->SetName("WToLNu");  
  TT     ->SetName("TT"); 
  ST     ->SetName("ST");  
  VV     ->SetName("VV");  
  cout<<"this step is ok 2"<<endl;
  tptzm0700lh->SetName("tptzm0700lh");
  tptzm0800lh->SetName("tptzm0800lh");
  tptzm0900lh->SetName("tptzm0900lh");
  tptzm1000lh->SetName("tptzm1000lh");
  tptzm1100lh->SetName("tptzm1100lh");
  tptzm1200lh->SetName("tptzm1200lh");
  tptzm1300lh->SetName("tptzm1300lh");
  tptzm1400lh->SetName("tptzm1400lh");
  tptzm1500lh->SetName("tptzm1500lh");
  tptzm1600lh->SetName("tptzm1600lh");
  tptzm1700lh->SetName("tptzm1700lh");
  tptzm1800lh->SetName("tptzm1800lh");
  cout<<"this step is ok 3"<<endl;
  ZToNuNu->Write();
  QCD    ->Write();
  WToLNu ->Write();
  TT     ->Write();
  ST     ->Write(); 
  VV     ->Write();  
  tptzm0700lh->Write();
  tptzm0800lh->Write();
  tptzm0900lh->Write();
  tptzm1000lh->Write();
  tptzm1100lh->Write();
  tptzm1200lh->Write();
  tptzm1300lh->Write();
  tptzm1400lh->Write();
  tptzm1500lh->Write();
  tptzm1600lh->Write();
  tptzm1700lh->Write();
  cout<<"this step is ok 4"<<endl;
  TH1F *data_obs=(TH1F*)data->Clone();
  data_obs->SetName("data_obs");
  data_obs->Write();

  /*TH1F *QCD_MCUp=(TH1F*)QCD->Clone();
  TH1F *QCD_MCDown=(TH1F*)QCD->Clone();
  for (int i=1; i<16; i++ ){
    QCD_MCUp->SetBinContent(i,QCD_MCUp->GetBinContent(i)+QCD_MCUp->GetBinError(i));
	QCD_MCDown->SetBinContent(i,QCD_MCDown->GetBinContent(i)-QCD_MCDown->GetBinError(i));
  }
  QCD_MCUp->Write();
  QCD_MCDown->Write();

  TH1F *ST_MCUp=(TH1F*)ST->Clone();
  TH1F *ST_MCDown=(TH1F*)ST->Clone();
  for (int i=1; i<16; i++ ){
    ST_MCUp->SetBinContent(i,ST_MCUp->GetBinContent(i)+ST_MCUp->GetBinError(i));
	ST_MCDown->SetBinContent(i,ST_MCDown->GetBinContent(i)-ST_MCDown->GetBinError(i));
  }
  ST_MCUp->Write();
  ST_MCDown->Write();

  TH1F *VV_MCUp=(TH1F*)VV->Clone();
  TH1F *VV_MCDown=(TH1F*)VV->Clone();
  for (int i=1; i<16; i++ ){
    VV_MCUp->SetBinContent(i,VV_MCUp->GetBinContent(i)+VV_MCUp->GetBinError(i));
	VV_MCDown->SetBinContent(i,VV_MCDown->GetBinContent(i)-VV_MCDown->GetBinError(i));
  }
  VV_MCUp->Write();
  VV_MCDown->Write();*/
  cout<<"this step is ok 5"<<endl;
  TH1F *QCD_bin1MCUp=(TH1F*)QCD->Clone();
  TH1F *QCD_bin2MCUp=(TH1F*)QCD->Clone();
  TH1F *QCD_bin3MCUp=(TH1F*)QCD->Clone();
  TH1F *QCD_bin4MCUp=(TH1F*)QCD->Clone();
  TH1F *QCD_bin5MCUp=(TH1F*)QCD->Clone();
  TH1F *QCD_bin6MCUp=(TH1F*)QCD->Clone();
  TH1F *QCD_bin7MCUp=(TH1F*)QCD->Clone();
  TH1F *QCD_bin8MCUp=(TH1F*)QCD->Clone();
  TH1F *QCD_bin9MCUp=(TH1F*)QCD->Clone();
  TH1F *QCD_bin10MCUp=(TH1F*)QCD->Clone();
  TH1F *QCD_bin11MCUp=(TH1F*)QCD->Clone();
  TH1F *QCD_bin12MCUp=(TH1F*)QCD->Clone();
  TH1F *QCD_bin13MCUp=(TH1F*)QCD->Clone();
  TH1F *QCD_bin14MCUp=(TH1F*)QCD->Clone();
  TH1F *QCD_bin15MCUp=(TH1F*)QCD->Clone();
  TH1F *QCD_bin1MCDown=(TH1F*)QCD->Clone();
  TH1F *QCD_bin2MCDown=(TH1F*)QCD->Clone();
  TH1F *QCD_bin3MCDown=(TH1F*)QCD->Clone();
  TH1F *QCD_bin4MCDown=(TH1F*)QCD->Clone();
  TH1F *QCD_bin5MCDown=(TH1F*)QCD->Clone();
  TH1F *QCD_bin6MCDown=(TH1F*)QCD->Clone();
  TH1F *QCD_bin7MCDown=(TH1F*)QCD->Clone();
  TH1F *QCD_bin8MCDown=(TH1F*)QCD->Clone();
  TH1F *QCD_bin9MCDown=(TH1F*)QCD->Clone();
  TH1F *QCD_bin10MCDown=(TH1F*)QCD->Clone();
  TH1F *QCD_bin11MCDown=(TH1F*)QCD->Clone();
  TH1F *QCD_bin12MCDown=(TH1F*)QCD->Clone();
  TH1F *QCD_bin13MCDown=(TH1F*)QCD->Clone();
  TH1F *QCD_bin14MCDown=(TH1F*)QCD->Clone();
  TH1F *QCD_bin15MCDown=(TH1F*)QCD->Clone();
  QCD_bin1MCUp->SetName("QCD_bin1MCUp");
  QCD_bin2MCUp->SetName("QCD_bin2MCUp");
  QCD_bin3MCUp->SetName("QCD_bin3MCUp");
  QCD_bin4MCUp->SetName("QCD_bin4MCUp");
  QCD_bin5MCUp->SetName("QCD_bin5MCUp");
  QCD_bin6MCUp->SetName("QCD_bin6MCUp");
  QCD_bin7MCUp->SetName("QCD_bin7MCUp");
  QCD_bin8MCUp->SetName("QCD_bin8MCUp");
  QCD_bin9MCUp->SetName("QCD_bin9MCUp");
  QCD_bin10MCUp->SetName("QCD_bin10MCUp");
  QCD_bin11MCUp->SetName("QCD_bin11MCUp");
  QCD_bin12MCUp->SetName("QCD_bin12MCUp");
  QCD_bin13MCUp->SetName("QCD_bin13MCUp");
  QCD_bin14MCUp->SetName("QCD_bin14MCUp");
  QCD_bin15MCUp->SetName("QCD_bin15MCUp");
  QCD_bin1MCDown->SetName("QCD_bin1MCDown");
  QCD_bin2MCDown->SetName("QCD_bin2MCDown");
  QCD_bin3MCDown->SetName("QCD_bin3MCDown");
  QCD_bin4MCDown->SetName("QCD_bin4MCDown");
  QCD_bin5MCDown->SetName("QCD_bin5MCDown");
  QCD_bin6MCDown->SetName("QCD_bin6MCDown");
  QCD_bin7MCDown->SetName("QCD_bin7MCDown");
  QCD_bin8MCDown->SetName("QCD_bin8MCDown");
  QCD_bin9MCDown->SetName("QCD_bin9MCDown");
  QCD_bin10MCDown->SetName("QCD_bin10MCDown");
  QCD_bin11MCDown->SetName("QCD_bin11MCDown");
  QCD_bin12MCDown->SetName("QCD_bin12MCDown");
  QCD_bin13MCDown->SetName("QCD_bin13MCDown");
  QCD_bin14MCDown->SetName("QCD_bin14MCDown");
  QCD_bin15MCDown->SetName("QCD_bin15MCDown");
  QCD_bin1MCUp->SetBinContent(1,QCD_bin1MCUp->GetBinContent(1)+QCD_bin1MCUp->GetBinError(1));
  QCD_bin2MCUp->SetBinContent(2,QCD_bin2MCUp->GetBinContent(2)+QCD_bin2MCUp->GetBinError(2));
  QCD_bin3MCUp->SetBinContent(3,QCD_bin3MCUp->GetBinContent(3)+QCD_bin3MCUp->GetBinError(3));
  QCD_bin4MCUp->SetBinContent(4,QCD_bin4MCUp->GetBinContent(4)+QCD_bin4MCUp->GetBinError(4));
  QCD_bin5MCUp->SetBinContent(5,QCD_bin5MCUp->GetBinContent(5)+QCD_bin5MCUp->GetBinError(5));
  QCD_bin6MCUp->SetBinContent(6,QCD_bin6MCUp->GetBinContent(6)+QCD_bin6MCUp->GetBinError(6));
  QCD_bin7MCUp->SetBinContent(7,QCD_bin7MCUp->GetBinContent(7)+QCD_bin7MCUp->GetBinError(7));
  QCD_bin8MCUp->SetBinContent(8,QCD_bin8MCUp->GetBinContent(8)+QCD_bin8MCUp->GetBinError(8));
  QCD_bin9MCUp->SetBinContent(9,QCD_bin9MCUp->GetBinContent(9)+QCD_bin9MCUp->GetBinError(9));
  QCD_bin10MCUp->SetBinContent(10,QCD_bin10MCUp->GetBinContent(10)+QCD_bin10MCUp->GetBinError(10));
  QCD_bin11MCUp->SetBinContent(11,QCD_bin11MCUp->GetBinContent(11)+QCD_bin11MCUp->GetBinError(11));
  QCD_bin12MCUp->SetBinContent(12,QCD_bin12MCUp->GetBinContent(12)+QCD_bin12MCUp->GetBinError(12));
  QCD_bin13MCUp->SetBinContent(13,QCD_bin13MCUp->GetBinContent(13)+QCD_bin13MCUp->GetBinError(13));
  QCD_bin14MCUp->SetBinContent(14,QCD_bin14MCUp->GetBinContent(14)+QCD_bin14MCUp->GetBinError(14));
  QCD_bin15MCUp->SetBinContent(15,QCD_bin15MCUp->GetBinContent(15)+QCD_bin15MCUp->GetBinError(15));
  QCD_bin1MCDown->SetBinContent(1,QCD_bin1MCDown->GetBinContent(1)-QCD_bin1MCDown->GetBinError(1));
  QCD_bin2MCDown->SetBinContent(2,QCD_bin2MCDown->GetBinContent(2)-QCD_bin2MCDown->GetBinError(2));
  QCD_bin3MCDown->SetBinContent(3,QCD_bin3MCDown->GetBinContent(3)-QCD_bin3MCDown->GetBinError(3));
  QCD_bin4MCDown->SetBinContent(4,QCD_bin4MCDown->GetBinContent(4)-QCD_bin4MCDown->GetBinError(4));
  QCD_bin5MCDown->SetBinContent(5,QCD_bin5MCDown->GetBinContent(5)-QCD_bin5MCDown->GetBinError(5));
  QCD_bin6MCDown->SetBinContent(6,QCD_bin6MCDown->GetBinContent(6)-QCD_bin6MCDown->GetBinError(6));
  QCD_bin7MCDown->SetBinContent(7,QCD_bin7MCDown->GetBinContent(7)-QCD_bin7MCDown->GetBinError(7));
  QCD_bin8MCDown->SetBinContent(8,QCD_bin8MCDown->GetBinContent(8)-QCD_bin8MCDown->GetBinError(8));
  QCD_bin9MCDown->SetBinContent(9,QCD_bin9MCDown->GetBinContent(9)-QCD_bin9MCDown->GetBinError(9));
  QCD_bin10MCDown->SetBinContent(10,QCD_bin10MCDown->GetBinContent(10)-QCD_bin10MCDown->GetBinError(10));
  QCD_bin11MCDown->SetBinContent(11,QCD_bin11MCDown->GetBinContent(11)-QCD_bin11MCDown->GetBinError(11));
  QCD_bin12MCDown->SetBinContent(12,QCD_bin12MCDown->GetBinContent(12)-QCD_bin12MCDown->GetBinError(12));
  QCD_bin13MCDown->SetBinContent(13,QCD_bin13MCDown->GetBinContent(13)-QCD_bin13MCDown->GetBinError(13));
  QCD_bin14MCDown->SetBinContent(14,QCD_bin14MCDown->GetBinContent(14)-QCD_bin14MCDown->GetBinError(14));
  QCD_bin15MCDown->SetBinContent(15,QCD_bin15MCDown->GetBinContent(15)-QCD_bin15MCDown->GetBinError(15));
  QCD_bin1MCUp->Write();
  QCD_bin2MCUp->Write();
  QCD_bin3MCUp->Write();
  QCD_bin4MCUp->Write();
  QCD_bin5MCUp->Write();
  QCD_bin6MCUp->Write();
  QCD_bin7MCUp->Write();
  QCD_bin8MCUp->Write();
  QCD_bin9MCUp->Write();
  QCD_bin10MCUp->Write();
  QCD_bin11MCUp->Write();
  QCD_bin12MCUp->Write();
  QCD_bin13MCUp->Write();
  QCD_bin14MCUp->Write();
  QCD_bin15MCUp->Write();
  QCD_bin1MCDown->Write();
  QCD_bin2MCDown->Write();
  QCD_bin3MCDown->Write();
  QCD_bin4MCDown->Write();
  QCD_bin5MCDown->Write();
  QCD_bin6MCDown->Write();
  QCD_bin7MCDown->Write();
  QCD_bin8MCDown->Write();
  QCD_bin9MCDown->Write();
  QCD_bin10MCDown->Write();
  QCD_bin11MCDown->Write();
  QCD_bin12MCDown->Write();
  QCD_bin13MCDown->Write();
  QCD_bin14MCDown->Write();
  QCD_bin15MCDown->Write();

  TH1F *ST_bin1MCUp=(TH1F*)ST->Clone();
  TH1F *ST_bin2MCUp=(TH1F*)ST->Clone();
  TH1F *ST_bin3MCUp=(TH1F*)ST->Clone();
  TH1F *ST_bin4MCUp=(TH1F*)ST->Clone();
  TH1F *ST_bin5MCUp=(TH1F*)ST->Clone();
  TH1F *ST_bin6MCUp=(TH1F*)ST->Clone();
  TH1F *ST_bin7MCUp=(TH1F*)ST->Clone();
  TH1F *ST_bin8MCUp=(TH1F*)ST->Clone();
  TH1F *ST_bin9MCUp=(TH1F*)ST->Clone();
  TH1F *ST_bin10MCUp=(TH1F*)ST->Clone();
  TH1F *ST_bin11MCUp=(TH1F*)ST->Clone();
  TH1F *ST_bin12MCUp=(TH1F*)ST->Clone();
  TH1F *ST_bin13MCUp=(TH1F*)ST->Clone();
  TH1F *ST_bin14MCUp=(TH1F*)ST->Clone();
  TH1F *ST_bin15MCUp=(TH1F*)ST->Clone();
  TH1F *ST_bin1MCDown=(TH1F*)ST->Clone();
  TH1F *ST_bin2MCDown=(TH1F*)ST->Clone();
  TH1F *ST_bin3MCDown=(TH1F*)ST->Clone();
  TH1F *ST_bin4MCDown=(TH1F*)ST->Clone();
  TH1F *ST_bin5MCDown=(TH1F*)ST->Clone();
  TH1F *ST_bin6MCDown=(TH1F*)ST->Clone();
  TH1F *ST_bin7MCDown=(TH1F*)ST->Clone();
  TH1F *ST_bin8MCDown=(TH1F*)ST->Clone();
  TH1F *ST_bin9MCDown=(TH1F*)ST->Clone();
  TH1F *ST_bin10MCDown=(TH1F*)ST->Clone();
  TH1F *ST_bin11MCDown=(TH1F*)ST->Clone();
  TH1F *ST_bin12MCDown=(TH1F*)ST->Clone();
  TH1F *ST_bin13MCDown=(TH1F*)ST->Clone();
  TH1F *ST_bin14MCDown=(TH1F*)ST->Clone();
  TH1F *ST_bin15MCDown=(TH1F*)ST->Clone();
  ST_bin1MCUp->SetName("ST_bin1MCUp");
  ST_bin2MCUp->SetName("ST_bin2MCUp");
  ST_bin3MCUp->SetName("ST_bin3MCUp");
  ST_bin4MCUp->SetName("ST_bin4MCUp");
  ST_bin5MCUp->SetName("ST_bin5MCUp");
  ST_bin6MCUp->SetName("ST_bin6MCUp");
  ST_bin7MCUp->SetName("ST_bin7MCUp");
  ST_bin8MCUp->SetName("ST_bin8MCUp");
  ST_bin9MCUp->SetName("ST_bin9MCUp");
  ST_bin10MCUp->SetName("ST_bin10MCUp");
  ST_bin11MCUp->SetName("ST_bin11MCUp");
  ST_bin12MCUp->SetName("ST_bin12MCUp");
  ST_bin13MCUp->SetName("ST_bin13MCUp");
  ST_bin14MCUp->SetName("ST_bin14MCUp");
  ST_bin15MCUp->SetName("ST_bin15MCUp");
  ST_bin1MCDown->SetName("ST_bin1MCDown");
  ST_bin2MCDown->SetName("ST_bin2MCDown");
  ST_bin3MCDown->SetName("ST_bin3MCDown");
  ST_bin4MCDown->SetName("ST_bin4MCDown");
  ST_bin5MCDown->SetName("ST_bin5MCDown");
  ST_bin6MCDown->SetName("ST_bin6MCDown");
  ST_bin7MCDown->SetName("ST_bin7MCDown");
  ST_bin8MCDown->SetName("ST_bin8MCDown");
  ST_bin9MCDown->SetName("ST_bin9MCDown");
  ST_bin10MCDown->SetName("ST_bin10MCDown");
  ST_bin11MCDown->SetName("ST_bin11MCDown");
  ST_bin12MCDown->SetName("ST_bin12MCDown");
  ST_bin13MCDown->SetName("ST_bin13MCDown");
  ST_bin14MCDown->SetName("ST_bin14MCDown");
  ST_bin15MCDown->SetName("ST_bin15MCDown");
  ST_bin1MCUp->SetBinContent(1,ST_bin1MCUp->GetBinContent(1)+ST_bin1MCUp->GetBinError(1));
  ST_bin2MCUp->SetBinContent(2,ST_bin2MCUp->GetBinContent(2)+ST_bin2MCUp->GetBinError(2));
  ST_bin3MCUp->SetBinContent(3,ST_bin3MCUp->GetBinContent(3)+ST_bin3MCUp->GetBinError(3));
  ST_bin4MCUp->SetBinContent(4,ST_bin4MCUp->GetBinContent(4)+ST_bin4MCUp->GetBinError(4));
  ST_bin5MCUp->SetBinContent(5,ST_bin5MCUp->GetBinContent(5)+ST_bin5MCUp->GetBinError(5));
  ST_bin6MCUp->SetBinContent(6,ST_bin6MCUp->GetBinContent(6)+ST_bin6MCUp->GetBinError(6));
  ST_bin7MCUp->SetBinContent(7,ST_bin7MCUp->GetBinContent(7)+ST_bin7MCUp->GetBinError(7));
  ST_bin8MCUp->SetBinContent(8,ST_bin8MCUp->GetBinContent(8)+ST_bin8MCUp->GetBinError(8));
  ST_bin9MCUp->SetBinContent(9,ST_bin9MCUp->GetBinContent(9)+ST_bin9MCUp->GetBinError(9));
  ST_bin10MCUp->SetBinContent(10,ST_bin10MCUp->GetBinContent(10)+ST_bin10MCUp->GetBinError(10));
  ST_bin11MCUp->SetBinContent(11,ST_bin11MCUp->GetBinContent(11)+ST_bin11MCUp->GetBinError(11));
  ST_bin12MCUp->SetBinContent(12,ST_bin12MCUp->GetBinContent(12)+ST_bin12MCUp->GetBinError(12));
  ST_bin12MCUp->SetBinContent(13,ST_bin12MCUp->GetBinContent(13)+ST_bin12MCUp->GetBinError(13));
  ST_bin12MCUp->SetBinContent(14,ST_bin12MCUp->GetBinContent(14)+ST_bin12MCUp->GetBinError(14));
  ST_bin12MCUp->SetBinContent(15,ST_bin12MCUp->GetBinContent(15)+ST_bin12MCUp->GetBinError(15));
  ST_bin1MCDown->SetBinContent(1,ST_bin1MCDown->GetBinContent(1)-ST_bin1MCDown->GetBinError(1));
  ST_bin2MCDown->SetBinContent(2,ST_bin2MCDown->GetBinContent(2)-ST_bin2MCDown->GetBinError(2));
  ST_bin3MCDown->SetBinContent(3,ST_bin3MCDown->GetBinContent(3)-ST_bin3MCDown->GetBinError(3));
  ST_bin4MCDown->SetBinContent(4,ST_bin4MCDown->GetBinContent(4)-ST_bin4MCDown->GetBinError(4));
  ST_bin5MCDown->SetBinContent(5,ST_bin5MCDown->GetBinContent(5)-ST_bin5MCDown->GetBinError(5));
  ST_bin6MCDown->SetBinContent(6,ST_bin6MCDown->GetBinContent(6)-ST_bin6MCDown->GetBinError(6));
  ST_bin7MCDown->SetBinContent(7,ST_bin7MCDown->GetBinContent(7)-ST_bin7MCDown->GetBinError(7));
  ST_bin8MCDown->SetBinContent(8,ST_bin8MCDown->GetBinContent(8)-ST_bin8MCDown->GetBinError(8));
  ST_bin9MCDown->SetBinContent(9,ST_bin9MCDown->GetBinContent(9)-ST_bin9MCDown->GetBinError(9));
  ST_bin10MCDown->SetBinContent(10,ST_bin10MCDown->GetBinContent(10)-ST_bin10MCDown->GetBinError(10));
  ST_bin11MCDown->SetBinContent(11,ST_bin11MCDown->GetBinContent(11)-ST_bin11MCDown->GetBinError(11));
  ST_bin12MCDown->SetBinContent(12,ST_bin12MCDown->GetBinContent(12)-ST_bin12MCDown->GetBinError(12));
  ST_bin13MCDown->SetBinContent(13,ST_bin13MCDown->GetBinContent(13)-ST_bin13MCDown->GetBinError(13));
  ST_bin14MCDown->SetBinContent(14,ST_bin14MCDown->GetBinContent(14)-ST_bin14MCDown->GetBinError(14));
  ST_bin15MCDown->SetBinContent(15,ST_bin15MCDown->GetBinContent(15)-ST_bin15MCDown->GetBinError(15));
  ST_bin1MCUp->Write();
  ST_bin2MCUp->Write();
  ST_bin3MCUp->Write();
  ST_bin4MCUp->Write();
  ST_bin5MCUp->Write();
  ST_bin6MCUp->Write();
  ST_bin7MCUp->Write();
  ST_bin8MCUp->Write();
  ST_bin9MCUp->Write();
  ST_bin10MCUp->Write();
  ST_bin11MCUp->Write();
  ST_bin12MCUp->Write();
  ST_bin13MCUp->Write();
  ST_bin14MCUp->Write();
  ST_bin15MCUp->Write();
  ST_bin1MCDown->Write();
  ST_bin2MCDown->Write();
  ST_bin3MCDown->Write();
  ST_bin4MCDown->Write();
  ST_bin5MCDown->Write();
  ST_bin6MCDown->Write();
  ST_bin7MCDown->Write();
  ST_bin8MCDown->Write();
  ST_bin9MCDown->Write();
  ST_bin10MCDown->Write();
  ST_bin11MCDown->Write();
  ST_bin12MCDown->Write();
  ST_bin13MCDown->Write();
  ST_bin14MCDown->Write();
  ST_bin15MCDown->Write();

  TH1F *VV_bin1MCUp=(TH1F*)VV->Clone();
  TH1F *VV_bin2MCUp=(TH1F*)VV->Clone();
  TH1F *VV_bin3MCUp=(TH1F*)VV->Clone();
  TH1F *VV_bin4MCUp=(TH1F*)VV->Clone();
  TH1F *VV_bin5MCUp=(TH1F*)VV->Clone();
  TH1F *VV_bin6MCUp=(TH1F*)VV->Clone();
  TH1F *VV_bin7MCUp=(TH1F*)VV->Clone();
  TH1F *VV_bin8MCUp=(TH1F*)VV->Clone();
  TH1F *VV_bin9MCUp=(TH1F*)VV->Clone();
  TH1F *VV_bin10MCUp=(TH1F*)VV->Clone();
  TH1F *VV_bin11MCUp=(TH1F*)VV->Clone();
  TH1F *VV_bin12MCUp=(TH1F*)VV->Clone();
  TH1F *VV_bin13MCUp=(TH1F*)VV->Clone();
  TH1F *VV_bin14MCUp=(TH1F*)VV->Clone();
  TH1F *VV_bin15MCUp=(TH1F*)VV->Clone();
  TH1F *VV_bin1MCDown=(TH1F*)VV->Clone();
  TH1F *VV_bin2MCDown=(TH1F*)VV->Clone();
  TH1F *VV_bin3MCDown=(TH1F*)VV->Clone();
  TH1F *VV_bin4MCDown=(TH1F*)VV->Clone();
  TH1F *VV_bin5MCDown=(TH1F*)VV->Clone();
  TH1F *VV_bin6MCDown=(TH1F*)VV->Clone();
  TH1F *VV_bin7MCDown=(TH1F*)VV->Clone();
  TH1F *VV_bin8MCDown=(TH1F*)VV->Clone();
  TH1F *VV_bin9MCDown=(TH1F*)VV->Clone();
  TH1F *VV_bin10MCDown=(TH1F*)VV->Clone();
  TH1F *VV_bin11MCDown=(TH1F*)VV->Clone();
  TH1F *VV_bin12MCDown=(TH1F*)VV->Clone();
  TH1F *VV_bin13MCDown=(TH1F*)VV->Clone();
  TH1F *VV_bin14MCDown=(TH1F*)VV->Clone();
  TH1F *VV_bin15MCDown=(TH1F*)VV->Clone();
  VV_bin1MCUp->SetName("VV_bin1MCUp");
  VV_bin2MCUp->SetName("VV_bin2MCUp");
  VV_bin3MCUp->SetName("VV_bin3MCUp");
  VV_bin4MCUp->SetName("VV_bin4MCUp");
  VV_bin5MCUp->SetName("VV_bin5MCUp");
  VV_bin6MCUp->SetName("VV_bin6MCUp");
  VV_bin7MCUp->SetName("VV_bin7MCUp");
  VV_bin8MCUp->SetName("VV_bin8MCUp");
  VV_bin9MCUp->SetName("VV_bin9MCUp");
  VV_bin10MCUp->SetName("VV_bin10MCUp");
  VV_bin11MCUp->SetName("VV_bin11MCUp");
  VV_bin12MCUp->SetName("VV_bin12MCUp");
  VV_bin13MCUp->SetName("VV_bin13MCUp");
  VV_bin14MCUp->SetName("VV_bin14MCUp");
  VV_bin15MCUp->SetName("VV_bin15MCUp");
  VV_bin1MCDown->SetName("VV_bin1MCDown");
  VV_bin2MCDown->SetName("VV_bin2MCDown");
  VV_bin3MCDown->SetName("VV_bin3MCDown");
  VV_bin4MCDown->SetName("VV_bin4MCDown");
  VV_bin5MCDown->SetName("VV_bin5MCDown");
  VV_bin6MCDown->SetName("VV_bin6MCDown");
  VV_bin7MCDown->SetName("VV_bin7MCDown");
  VV_bin8MCDown->SetName("VV_bin8MCDown");
  VV_bin9MCDown->SetName("VV_bin9MCDown");
  VV_bin10MCDown->SetName("VV_bin10MCDown");
  VV_bin11MCDown->SetName("VV_bin11MCDown");
  VV_bin12MCDown->SetName("VV_bin12MCDown");
  VV_bin13MCDown->SetName("VV_bin13MCDown");
  VV_bin14MCDown->SetName("VV_bin14MCDown");
  VV_bin15MCDown->SetName("VV_bin15MCDown");
  VV_bin1MCUp->SetBinContent(1,VV_bin1MCUp->GetBinContent(1)+VV_bin1MCUp->GetBinError(1));
  VV_bin2MCUp->SetBinContent(2,VV_bin2MCUp->GetBinContent(2)+VV_bin2MCUp->GetBinError(2));
  VV_bin3MCUp->SetBinContent(3,VV_bin3MCUp->GetBinContent(3)+VV_bin3MCUp->GetBinError(3));
  VV_bin4MCUp->SetBinContent(4,VV_bin4MCUp->GetBinContent(4)+VV_bin4MCUp->GetBinError(4));
  VV_bin5MCUp->SetBinContent(5,VV_bin5MCUp->GetBinContent(5)+VV_bin5MCUp->GetBinError(5));
  VV_bin6MCUp->SetBinContent(6,VV_bin6MCUp->GetBinContent(6)+VV_bin6MCUp->GetBinError(6));
  VV_bin7MCUp->SetBinContent(7,VV_bin7MCUp->GetBinContent(7)+VV_bin7MCUp->GetBinError(7));
  VV_bin8MCUp->SetBinContent(8,VV_bin8MCUp->GetBinContent(8)+VV_bin8MCUp->GetBinError(8));
  VV_bin9MCUp->SetBinContent(9,VV_bin9MCUp->GetBinContent(9)+VV_bin9MCUp->GetBinError(9));
  VV_bin10MCUp->SetBinContent(10,VV_bin10MCUp->GetBinContent(10)+VV_bin10MCUp->GetBinError(10));
  VV_bin11MCUp->SetBinContent(11,VV_bin11MCUp->GetBinContent(11)+VV_bin11MCUp->GetBinError(11));
  VV_bin12MCUp->SetBinContent(12,VV_bin12MCUp->GetBinContent(12)+VV_bin12MCUp->GetBinError(12));
  VV_bin13MCUp->SetBinContent(13,VV_bin13MCUp->GetBinContent(13)+VV_bin13MCUp->GetBinError(13));
  VV_bin14MCUp->SetBinContent(14,VV_bin14MCUp->GetBinContent(14)+VV_bin14MCUp->GetBinError(14));
  VV_bin15MCUp->SetBinContent(15,VV_bin15MCUp->GetBinContent(15)+VV_bin15MCUp->GetBinError(15));
  VV_bin1MCDown->SetBinContent(1,VV_bin1MCDown->GetBinContent(1)-VV_bin1MCDown->GetBinError(1));
  VV_bin2MCDown->SetBinContent(2,VV_bin2MCDown->GetBinContent(2)-VV_bin2MCDown->GetBinError(2));
  VV_bin3MCDown->SetBinContent(3,VV_bin3MCDown->GetBinContent(3)-VV_bin3MCDown->GetBinError(3));
  VV_bin4MCDown->SetBinContent(4,VV_bin4MCDown->GetBinContent(4)-VV_bin4MCDown->GetBinError(4));
  VV_bin5MCDown->SetBinContent(5,VV_bin5MCDown->GetBinContent(5)-VV_bin5MCDown->GetBinError(5));
  VV_bin6MCDown->SetBinContent(6,VV_bin6MCDown->GetBinContent(6)-VV_bin6MCDown->GetBinError(6));
  VV_bin7MCDown->SetBinContent(7,VV_bin7MCDown->GetBinContent(7)-VV_bin7MCDown->GetBinError(7));
  VV_bin8MCDown->SetBinContent(8,VV_bin8MCDown->GetBinContent(8)-VV_bin8MCDown->GetBinError(8));
  VV_bin9MCDown->SetBinContent(9,VV_bin9MCDown->GetBinContent(9)-VV_bin9MCDown->GetBinError(9));
  VV_bin10MCDown->SetBinContent(10,VV_bin10MCDown->GetBinContent(10)-VV_bin10MCDown->GetBinError(10));
  VV_bin11MCDown->SetBinContent(11,VV_bin11MCDown->GetBinContent(11)-VV_bin11MCDown->GetBinError(11));
  VV_bin12MCDown->SetBinContent(12,VV_bin12MCDown->GetBinContent(12)-VV_bin12MCDown->GetBinError(12));
  VV_bin13MCDown->SetBinContent(13,VV_bin13MCDown->GetBinContent(13)-VV_bin13MCDown->GetBinError(13));
  VV_bin14MCDown->SetBinContent(14,VV_bin14MCDown->GetBinContent(14)-VV_bin14MCDown->GetBinError(14));
  VV_bin15MCDown->SetBinContent(15,VV_bin15MCDown->GetBinContent(15)-VV_bin15MCDown->GetBinError(15));
  VV_bin1MCUp->Write();
  VV_bin2MCUp->Write();
  VV_bin3MCUp->Write();
  VV_bin4MCUp->Write();
  VV_bin5MCUp->Write();
  VV_bin6MCUp->Write();
  VV_bin7MCUp->Write();
  VV_bin8MCUp->Write();
  VV_bin9MCUp->Write();
  VV_bin10MCUp->Write();
  VV_bin11MCUp->Write();
  VV_bin12MCUp->Write();
  VV_bin13MCUp->Write();
  VV_bin14MCUp->Write();
  VV_bin15MCUp->Write();
  VV_bin1MCDown->Write();
  VV_bin2MCDown->Write();
  VV_bin3MCDown->Write();
  VV_bin4MCDown->Write();
  VV_bin5MCDown->Write();
  VV_bin6MCDown->Write();
  VV_bin7MCDown->Write();
  VV_bin8MCDown->Write();
  VV_bin9MCDown->Write();
  VV_bin10MCDown->Write();
  VV_bin11MCDown->Write();
  VV_bin12MCDown->Write();
  VV_bin13MCDown->Write();
  VV_bin14MCDown->Write();
  VV_bin15MCDown->Write();

  tptzm0700lh_bta1->SetName("tptzm0700lh_BTAGUp");
  tptzm0800lh_bta1->SetName("tptzm0800lh_BTAGUp");
  tptzm0900lh_bta1->SetName("tptzm0900lh_BTAGUp");
  tptzm1000lh_bta1->SetName("tptzm1000lh_BTAGUp");
  tptzm1100lh_bta1->SetName("tptzm1100lh_BTAGUp");
  tptzm1200lh_bta1->SetName("tptzm1200lh_BTAGUp");
  tptzm1300lh_bta1->SetName("tptzm1300lh_BTAGUp");
  tptzm1400lh_bta1->SetName("tptzm1400lh_BTAGUp");
  tptzm1500lh_bta1->SetName("tptzm1500lh_BTAGUp");
  tptzm1600lh_bta1->SetName("tptzm1600lh_BTAGUp");
  tptzm1700lh_bta1->SetName("tptzm1700lh_BTAGUp");
  tptzm1800lh_bta1->SetName("tptzm1800lh_BTAGUp");
  tptzm0700lh_bta2->SetName("tptzm0700lh_BTAGDown");
  tptzm0800lh_bta2->SetName("tptzm0800lh_BTAGDown");
  tptzm0900lh_bta2->SetName("tptzm0900lh_BTAGDown");
  tptzm1000lh_bta2->SetName("tptzm1000lh_BTAGDown");
  tptzm1100lh_bta2->SetName("tptzm1100lh_BTAGDown");
  tptzm1200lh_bta2->SetName("tptzm1200lh_BTAGDown");
  tptzm1300lh_bta2->SetName("tptzm1300lh_BTAGDown");
  tptzm1400lh_bta2->SetName("tptzm1400lh_BTAGDown");
  tptzm1500lh_bta2->SetName("tptzm1500lh_BTAGDown");
  tptzm1600lh_bta2->SetName("tptzm1600lh_BTAGDown");
  tptzm1700lh_bta2->SetName("tptzm1700lh_BTAGDown");
  tptzm1800lh_bta2->SetName("tptzm1800lh_BTAGDown");
  tptzm0700lh_bta1->Write();
  tptzm0800lh_bta1->Write();
  tptzm0900lh_bta1->Write();
  tptzm1000lh_bta1->Write();
  tptzm1100lh_bta1->Write();
  tptzm1200lh_bta1->Write();
  tptzm1300lh_bta1->Write();
  tptzm1400lh_bta1->Write();
  tptzm1500lh_bta1->Write();
  tptzm1600lh_bta1->Write();
  tptzm1700lh_bta1->Write();
  tptzm1800lh_bta1->Write();
  tptzm0700lh_bta2->Write();
  tptzm0800lh_bta2->Write();
  tptzm0900lh_bta2->Write();
  tptzm1000lh_bta2->Write();
  tptzm1100lh_bta2->Write();
  tptzm1200lh_bta2->Write();
  tptzm1300lh_bta2->Write();
  tptzm1400lh_bta2->Write();
  tptzm1500lh_bta2->Write();
  tptzm1600lh_bta2->Write();
  tptzm1700lh_bta2->Write();
  tptzm1800lh_bta2->Write();

  tptzm0700lh_pup1->SetName("tptzm0700lh_PUwUp");
  tptzm0800lh_pup1->SetName("tptzm0800lh_PUwUp");
  tptzm0900lh_pup1->SetName("tptzm0900lh_PUwUp");
  tptzm1000lh_pup1->SetName("tptzm1000lh_PUwUp");
  tptzm1100lh_pup1->SetName("tptzm1100lh_PUwUp");
  tptzm1200lh_pup1->SetName("tptzm1200lh_PUwUp");
  tptzm1300lh_pup1->SetName("tptzm1300lh_PUwUp");
  tptzm1400lh_pup1->SetName("tptzm1400lh_PUwUp");
  tptzm1500lh_pup1->SetName("tptzm1500lh_PUwUp");
  tptzm1600lh_pup1->SetName("tptzm1600lh_PUwUp");
  tptzm1700lh_pup1->SetName("tptzm1700lh_PUwUp");
  tptzm1800lh_pup1->SetName("tptzm1800lh_PUwUp");
  tptzm0700lh_pup2->SetName("tptzm0700lh_PUwDown");
  tptzm0800lh_pup2->SetName("tptzm0800lh_PUwDown");
  tptzm0900lh_pup2->SetName("tptzm0900lh_PUwDown");
  tptzm1000lh_pup2->SetName("tptzm1000lh_PUwDown");
  tptzm1100lh_pup2->SetName("tptzm1100lh_PUwDown");
  tptzm1200lh_pup2->SetName("tptzm1200lh_PUwDown");
  tptzm1300lh_pup2->SetName("tptzm1300lh_PUwDown");
  tptzm1400lh_pup2->SetName("tptzm1400lh_PUwDown");
  tptzm1500lh_pup2->SetName("tptzm1500lh_PUwDown");
  tptzm1600lh_pup2->SetName("tptzm1600lh_PUwDown");
  tptzm1700lh_pup2->SetName("tptzm1700lh_PUwDown");
  tptzm1800lh_pup2->SetName("tptzm1800lh_PUwDown");
  tptzm0700lh_pup1->Write();
  tptzm0800lh_pup1->Write();
  tptzm0900lh_pup1->Write();
  tptzm1000lh_pup1->Write();
  tptzm1100lh_pup1->Write();
  tptzm1200lh_pup1->Write();
  tptzm1300lh_pup1->Write();
  tptzm1400lh_pup1->Write();
  tptzm1500lh_pup1->Write();
  tptzm1600lh_pup1->Write();
  tptzm1700lh_pup1->Write();
  tptzm1800lh_pup1->Write();
  tptzm0700lh_pup2->Write();
  tptzm0800lh_pup2->Write();
  tptzm0900lh_pup2->Write();
  tptzm1000lh_pup2->Write();
  tptzm1100lh_pup2->Write();
  tptzm1200lh_pup2->Write();
  tptzm1300lh_pup2->Write();
  tptzm1400lh_pup2->Write();
  tptzm1500lh_pup2->Write();
  tptzm1600lh_pup2->Write();
  tptzm1700lh_pup2->Write();
  tptzm1800lh_pup2->Write();


  ZToNuNu_zje1->SetName("ZToNuNu_zjeUp");
  ZToNuNu_zje2->SetName("ZToNuNu_zjeDown");
  WToLNu_wje1->SetName("WToLNu_wjeUp");
  WToLNu_wje2->SetName("WToLNu_wjeDown");
  TT_ttb1->SetName("TT_ttbUp");
  TT_ttb2->SetName("TT_ttbDown");

  ZToNuNu_zje1->Write();
  ZToNuNu_zje2->Write();
  WToLNu_wje1->Write();
  WToLNu_wje2->Write();
  TT_ttb1->Write();
  TT_ttb2->Write();
  
  
  /*histo_PRE_bta1->SetName("background"+CAT+"_"+FRW+"_BkgBTAG"+CAT+"_"+FRW+"Up");
  histo_PRE_bta2->SetName("background"+CAT+"_"+FRW+"_BkgBTAG"+CAT+"_"+FRW+"Down");
  histo_PRE_bta1->Write();
  histo_PRE_bta2->Write();
  histo_PRE_zje1->SetName("background"+CAT+"_"+FRW+"_Zjet"+CAT+"_"+FRW+"Down");
  histo_PRE_zje2->SetName("background"+CAT+"_"+FRW+"_Zjet"+CAT+"_"+FRW+"Up");
  histo_PRE_zje1->Write();
  histo_PRE_zje2->Write();
  histo_PRE_clo1->SetName("background"+CAT+"_"+FRW+"_CLOS"+CAT+"_"+FRW+"Up");
  histo_PRE_clo2->SetName("background"+CAT+"_"+FRW+"_CLOS"+CAT+"_"+FRW+"Down");
  histo_PRE_clo1->Write();
  histo_PRE_clo2->Write();*/
}
